### ISSUE TITLE
Incorrect affiliation

### ISSUE THREAD

**Issue by yoavweiss** [w3c/ash-nazg#144]
Hey!

@jeremyroman seem to have the wrong affiliation in the ash-nazg DB, which doesn't match the one he has defined in his W3C account (Google).

Digging through affiliations, it seems that I'm my own affiliation is also off, and I'm still affiliated with my previous employer (Akamai), rather than my current one (Google).

Is there a way for users to fix their affiliation through the interface? I failed to find one.

**Comment by dontcallmedom** [comment]
From what I can see, @jeremyroman 's affiliation is correct - but his pull requests to WICG get flagged because [he has not been nominated to the group](https://www.w3.org/community/wicg/participants).

Your affiliation was indeed wrong, because you were associated with the system before it was plugged correctly into the W3C affiliation db - I think I have correctly fixed it, but let me know if you get errors out of this change.

**Comment by yoavweiss** [comment]
Thanks! :)
