### ISSUE TITLE
Business group repositories do not seem to be included in creation pull down

### ISSUE THREAD

**Issue by iherman** [w3c/ash-nazg#173]
A few days ago I tried to create a repository for a Business Group. I have added the Publishing Business Group to:

https://labs.w3.org/hatchery/repo-manager/admin/groups

However, when trying to create a repository using

https://labs.w3.org/hatchery/repo-manager/repo/new

business groups do not appear under the pull down menu. I think it should.

**Comment by dontcallmedom** [comment]
the repo manager is focused on IPR management, which I don't think typically applies to Business Group; if your primary goal is to create a repo with the well-known files, @plehegar and I had talked about setting up [template repositories](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) instead of trying to keep adding new files (e.g. per #170) to this tool.

Can you clarify what your intent is for the BG?

**Comment by iherman** [comment]
It is correct that I used the manager as some sort of a template; it is fairly useful in setting up a repo with some minimal content (LICENSE, w3c.json, etc.). I have used the service several times to create repos for WG Notes, for example, which are not subject of IPR either.

But then... why are Community Groups listed in the aforementioned pull down menu? BG-s are, in this respect, no different; CG-s are not subject of our IPR policy either...

**Comment by dontcallmedom** [comment]
(most) CGs need to track IPR commitment on the specs they develop

**Comment by iherman** [comment]
and why can I then add a BG in

https://labs.w3.org/hatchery/repo-manager/admin/groups ?

**Comment by dontcallmedom** [comment]
the (buggy) remain of a former support for this I guess :)
