### ISSUE TITLE
Missing "import repo" button

### ISSUE THREAD

**Issue by yoavweiss** [w3c/ash-nazg#199]
I'm currently logged in to repo manager, but missing the "import repo" option that enables me to... import repos
<img width="965" alt="Screen Shot 2021-02-03 at 20 04 20" src="https://user-images.githubusercontent.com/786187/106796490-b5051b80-665b-11eb-8440-c33b93e08d18.png">

Can y'all assist?

**Comment by dontcallmedom** [comment]
@deniak may this be related to the recent security fix? or  #187?

**Comment by dontcallmedom** [comment]
@yoavweiss meanwhile if you want us to do the import for you, we'll be happy to help while we debug the underlying issue

**Comment by yoavweiss** [comment]
Thanks! Already got it imported by someone else :)

**Comment by deniak** [comment]
In order to be able to import or create repositories from the repository manager, you will need to provide more github permissions.
In the login page, there are actually 2 links to log in. One for contributors and another one that will ask for more permissions.

![repo-login](https://user-images.githubusercontent.com/1696128/106845366-3d1f0b80-66c4-11eb-8c59-b8c8a877b4ed.png)

I believe you selected the first link which would explain why the import/create repo options were not listed.
Can you try to log out and log in again with the second?

**Comment by yoavweiss** [comment]
That did the trick! Thanks!
