### ISSUE TITLE
Stalled IPR bot in PR

### ISSUE THREAD

**Issue by tidoust** [w3c/ash-nazg#244]
Creating a proper report for that. As reported on IRC, the IPR bot has been stalling for gpuweb/gpuweb PRs in the past few days, see e.g. https://github.com/gpuweb/gpuweb/pull/2775, https://github.com/gpuweb/gpuweb/pull/2774 or https://github.com/gpuweb/gpuweb/pull/2767.

Check seems to have been done:
https://labs.w3.org/repo-manager/pr/id/gpuweb/gpuweb/2767
https://labs.w3.org/repo-manager/pr/id/gpuweb/gpuweb/2774
https://labs.w3.org/repo-manager/pr/id/gpuweb/gpuweb/2775

... but ipr check is still flagged as "pending" in the PR and trying to "revalidate" the PR through the admin UI yields a "PR not found" error message.

**Comment by deniak** [comment]
The webhook timed out for the recent requests due to a recent upgrade of couchdb that didn't complete. The repo manager was then unable to record the PR.
This should now be fixed.

For #2767, the reason is different though. It might be related to some network glitches we had over the weekend but I'll dig more.
