### ISSUE TITLE
"Cannot convert undefined or null to object" when revalidating

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/ash-nazg#39]
Not sure if this is related to the repo manager per se, or just how it's been hooked up specifically to this repo, but: doing a PR on https://github.com/w3c/Mobile-A11y-Extension/pull/9 resulted in an IPR failure (as I was, at the time, not part of the correct contributors list); trying to now trigger a revalidation on https://labs.w3.org/hatchery/repo-manager/pr/id/w3c/Mobile-A11y-Extension/9 i just get a "Cannot convert undefined or null to object" error and nothing further happens...

![capture](https://cloud.githubusercontent.com/assets/895831/16917399/635f3f2a-4cf9-11e6-94e7-8341e7ade6cd.PNG)

**Comment by patrickhlauke** [comment]
ping @dontcallmedom

**Comment by dontcallmedom** [comment]
so there is a combination of issues at work here; the reason you're not getting IPR imprimatur is that:
* your github account is not associated with the WCAG WG in ash-nazg
* it cannot be associated with the WCAG WG, since that WG has not been added to ash-nazg yet (which is easy to fix)
* the repo you're updating is not associated with the WCAG WG, but with the HTML WG

There seems to be furthermore a bug in how ash-nazg reports the error in this specific combination, which I'll need more time to investigate. I suspect that the fact that the `w3c.json` lists "shadi" instead of "nitedog" as the contact for the repo plays a role in it.

I suggest ignoring the IPR warnings for the time being; I'm not sure if they've ever been useful given that it looks like the repo was never correctly configured.

@nitedog any input on the above?

**Comment by dontcallmedom** [comment]
I've added the WCAG WG to ash-nazg, and associated @patrickhlauke to it; moving the repo to the right group is something not implemented in ash-nazg yet; I've filed #40 for this.

**Comment by patrickhlauke** [comment]
thanks @dontcallmedom ... sorry for opening a can of issue-worms there. i'll ignore the IPR warning for now :)

**Comment by nitedog** [comment]
I fixed the naming - was using the W3C rather than the GitHub handle. I think this repo should be associated with WCAG WG rather than HTML WG but I will double-check with @michael-n-cooper.

Sorry for these issues due to transition @patrickhlauke, don't we all miss @jspellman!

**Comment by michael-n-cooper** [comment]
I'm not understanding what the question is from reviewing the thread. I see stuff about the One Ring and Mobile Checker, both of which are not part of the WCAG repo.

**Comment by dontcallmedom** [comment]
@michael-n-cooper to be more specific, the https://github.com/w3c/Mobile-A11y-Extension/ repository belongs to the WCAG Working Group, not the HTML Working Group, right?

**Comment by michael-n-cooper** [comment]
Yes, that is correct.

**Comment by dontcallmedom** [comment]
The repo has now been associated to the right group (thanks to #41), so this issue I think is now solved, closing.
