### ISSUE TITLE
Error: "Could not retrieve email addresses from repos contacts"

### ISSUE THREAD

**Issue by wseltzer** [w3c/ash-nazg#65]
A user is correctly associated with Member and W3C group, but the IPR check fails with this message:
"Error: Could not retrieve email addresses from repos contacts"

**Comment by wseltzer** [comment]
Possibly, the problem is that the system lists two users with case-sensitive difference in username, one validated and one not.  This is the PR https://labs.w3.org/hatchery/repo-manager/pr/id/w3c/webauthn/333

**Comment by wseltzer** [comment]
(I flagged as non-substantive to enable work to proceed.)

**Comment by dontcallmedom** [comment]
there are two distinct issues here:
* while AngeloKai was known in ash-nazg, the association with his W3C account hadn't been recorded there, so ash-nazg could not validate his affiliation; I have done the association (via https://labs.w3.org/hatchery/repo-manager/admin/user/AngeloKai)

* none of the contacts associated with the repos in https://github.com/w3c/webauthn/blob/master/w3c.json have associated email addresses in github, so ash-nazg can't notify the error by email

Since this are operational issues and not a software bug, closing this

**Comment by wseltzer** [comment]
But there were two AngeloKai records, one of which *was* associated with W3C account, the other one I couldn't modify.

**Comment by dontcallmedom** [comment]
sorry, I was a bit short in my description of the problem - the `w3c.json` at the root of the repository has a list of contacts as github usernames, and none of these usernames (wseltzer, hhalpin) have a known email address in github.

(arguably, the tool could check if that user is known in its local database and find the email address from there when they are)

**Comment by wseltzer** [comment]
@dontcallmedom call me dense, but I don't know where to associate email addresses with username, apart from my account which certainly has emails associated.

**Comment by dontcallmedom** [comment]
my guess it that your [emails are marked as private](https://help.github.com/articles/keeping-your-email-address-private/) since it doesn't appear in the [GH API view of your account](https://api.github.com/users/wseltzer)

**Comment by wseltzer** [comment]
thanks, fixed that.
